version: '3.8'

services:
  db:
    image: postgres:16
    volumes:
      - data:/var/lib/postgresql/data
      - ./Database/crypto_db.sql:/docker-entrypoint-initdb.d/crypto_db.sql
    ports:
      - "5432:5432"
    env_file:
      - .env

  api:
    build: ./API
    restart: always
    env_file:
      - .env

volumes:
  data:
