version: '3.8'

services:

  db:
    image: mongo:5
    container_name: cit-db
    command: ['--bind_ip_all', '--port', '${DB_PORT}']
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - db:/data/db

  api:
    build:
      context: api
      dockerfile: Dockerfile
    container_name: cit-api
    env_file:
      - .env
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}

      API_PORT: ${API_PORT}
    
    ports:
      - ${API_PORT}:${API_PORT}
    restart: always

volumes:
  db:
    name: cit-db
