version: '3.8'

services:

  db:
    image: mongo:5
    container_name: cit-db
    command: ['--bind_ip_all', '--port', '${DB_PORT}']
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - db:/data/db
    healthcheck:
      test: test $$(echo "rs.initiate({_id:'rs0',members:[{_id:0,host:\"localhost:${DB_PORT}\"}]}).ok || rs.status().ok" | mongo --port ${DB_PORT} --quiet) -eq 1
      interval: 10s
      start_period: 30s

  api:
    build:
      context: api
      dockerfile: Dockerfile
    container_name: cit-api
    env_file:
      - .env
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}

      API_PORT: ${API_PORT}
      OLD_API_HOST: ${OLD_API_HOST}
    
    ports:
      - ${API_PORT}:${API_PORT}
    restart: always
    depends_on:
      - db

volumes:
  db:
    name: cit-db
